import { useEffect, useMemo, useState } from "react";
import { Gamepad2, RotateCcw } from "lucide-react";
import { ModalShell } from "../ui/ModalShell";

type Game = "tetris" | "2048" | "snake" | "memory";
interface GamesModalProps { open: boolean; onClose: () => void }
const games: { id: Game; label: string }[] = [{id:"tetris",label:"Tetris"},{id:"2048",label:"2048"},{id:"snake",label:"Snake"},{id:"memory",label:"Memory"}];

function MemoryGame(){const symbols=useMemo(()=>["⚡","⌘","◈","◆","⚡","⌘","◈","◆"].sort(()=>Math.random()-.5),[]);const[open,setOpen]=useState<number[]>([]),[done,setDone]=useState<number[]>([]);const choose=(i:number)=>{if(open.includes(i)||done.includes(i)||open.length===2)return;const next=[...open,i];setOpen(next);if(next.length===2)setTimeout(()=>{if(symbols[next[0]]===symbols[next[1]])setDone(v=>[...v,...next]);setOpen([])},450)};return <div className="memory-grid">{symbols.map((symbol,i)=><button key={i} onClick={()=>choose(i)} aria-label={`${open.includes(i)||done.includes(i)?symbol:"Hidden"} memory card`}>{open.includes(i)||done.includes(i)?symbol:"?"}</button>)}</div>}

function Game2048(){const[tiles,setTiles]=useState(()=>[2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0]);const move=()=>setTiles(old=>{const values=old.filter(Boolean);const merged:number[]=[];for(let i=0;i<values.length;i++){if(values[i]===values[i+1]){merged.push(values[i]*2);i++}else merged.push(values[i])}while(merged.length<16)merged.push(0);const empty=merged.map((v,i)=>v?null:i).filter((v):v is number=>v!==null);if(empty.length)merged[empty[Math.floor(Math.random()*empty.length)]]=Math.random()>.8?4:2;return merged});return <><div className="tile-grid">{tiles.map((v,i)=><div key={i} className={v?"filled":""}>{v||""}</div>)}</div><div className="game-controls"><button onClick={move}>Move / Merge</button><button onClick={()=>setTiles([2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0])}><RotateCcw/> Reset</button></div></>}

function SnakeGame(){const[size]=useState(8),[snake,setSnake]=useState([18,17,16]),[food,setFood]=useState(30),[direction,setDirection]=useState(1),[running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const timer=setInterval(()=>setSnake(old=>{const head=old[0],row=Math.floor(head/size),col=head%size;let next=direction===1?row*size+(col+1)%size:direction===-1?row*size+(col-1+size)%size:direction===size?((row+1)%size)*size+col:((row-1+size)%size)*size+col;if(old.includes(next)){setRunning(false);return old}const grown=next===food;const updated=[next,...old];if(!grown)updated.pop();else setFood(Math.floor(Math.random()*size*size));return updated}),220);return()=>clearInterval(timer)},[running,direction,food,size]);return <><div className="snake-grid">{Array.from({length:size*size},(_,i)=><div key={i} className={snake.includes(i)?"snake":i===food?"food":""}/>)}</div><div className="direction-pad"><button onClick={()=>setDirection(-size)}>↑</button><button onClick={()=>setDirection(-1)}>←</button><button onClick={()=>setRunning(v=>!v)}>{running?"Pause":"Play"}</button><button onClick={()=>setDirection(1)}>→</button><button onClick={()=>setDirection(size)}>↓</button></div></>}

function TetrisGame(){const[blocks,setBlocks]=useState([3,13,23]),[active,setActive]=useState(5);const drop=()=>setActive(v=>v+10>59?(setBlocks(old=>[...old,v]),Math.floor(Math.random()*10)):v+10);const move=(d:number)=>setActive(v=>Math.max(0,Math.min(59,v+d)));return <><div className="tetris-grid">{Array.from({length:60},(_,i)=><div key={i} className={i===active||blocks.includes(i)?"block":""}/>)}</div><div className="game-controls"><button onClick={()=>move(-1)}>←</button><button onClick={drop}>Drop</button><button onClick={()=>move(1)}>→</button><button onClick={()=>{setBlocks([3,13,23]);setActive(5)}}><RotateCcw/> Reset</button></div></>}

export function GamesModal({open,onClose}:GamesModalProps){const[selected,setSelected]=useState<Game>("tetris");return <ModalShell open={open} onClose={onClose} title="Mini Game Break"><div className="game-hub"><nav aria-label="Choose a game">{games.map(game=><button key={game.id} className={selected===game.id?"active":""} aria-pressed={selected===game.id} onClick={()=>setSelected(game.id)}>{game.label}</button>)}</nav><div className="game-stage"><p><Gamepad2 aria-hidden="true"/> Take a quick break</p>{selected==="tetris"&&<TetrisGame/>}{selected==="2048"&&<Game2048/>}{selected==="snake"&&<SnakeGame/>}{selected==="memory"&&<MemoryGame/>}</div></div></ModalShell>}
