import { useEffect, useState, type FormEvent } from "react";
import { motion, useReducedMotion } from "motion/react";
import { ArrowUp, Briefcase, Download, ExternalLink, FileText, Gamepad2, Github, GraduationCap, Mail, Send } from "lucide-react";
import { credentials, experience, projects, roles, skillGroups, type Project } from "../../data/portfolioData";
import { ModalShell } from "../ui/ModalShell";
import { SectionHeader } from "../ui/SectionHeader";
import { SocialLinks } from "../ui/SocialLinks";
import { GamesModal } from "../modals/GamesModal";

const reveal = { initial:{opacity:0,y:18}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.12}, transition:{duration:.45} };

export function HeroSection(){const reduce=useReducedMotion();const[index,setIndex]=useState(0),[gamesOpen,setGamesOpen]=useState(false);useEffect(()=>{if(reduce)return;const id=setInterval(()=>setIndex(v=>(v+1)%roles.length),2600);return()=>clearInterval(id)},[reduce]);return <><section id="hero" className="hero section"><div className="hero-copy"><p className="eyebrow">Hello, I’m Drix Molina</p><h1>Useful digital products, built with <span>clarity.</span></h1><p className="stable-role"><span aria-hidden="true">{reduce?roles[0]:roles[index]}</span><span className="sr-only">Full Stack Developer, IT Support Specialist, and AI Automation Developer</span></p><p className="hero-summary">IT graduate building accessible web experiences, dependable support solutions, and practical automation.</p><div className="hero-actions"><a className="button primary" href="#projects">View My Work</a><a className="button secondary" href="/resume/Drix_Molina_Resume.pdf" download>Resume <Download/></a><button className="button secondary game-button" type="button" onClick={()=>setGamesOpen(true)}><Gamepad2/> Play Games</button></div><a className="text-link" href="#contact">Contact Me →</a><SocialLinks/></div><div className="hero-visual glass"><img src="/profile/drix-portrait-new.png" width="640" height="800" alt="Portrait of Drix Molina" decoding="async"/><div className="availability"><span/>Available for opportunities</div></div></section><GamesModal open={gamesOpen} onClose={()=>setGamesOpen(false)}/></>}

export function ProjectsSection(){const[selected,setSelected]=useState<Project|null>(null);return <section id="projects" className="section"><SectionHeader eyebrow="Selected work" title="Featured Projects" description="Real systems built around operational needs, usability, and maintainable interfaces."/><div className="project-grid">{projects.map(p=><motion.article {...reveal} key={p.id} className="project-card glass"><img src={p.image} width="1200" height="675" loading="lazy" decoding="async" alt={`${p.title} interface preview`}/><div className="project-content"><h3>{p.title}</h3><dl><div><dt>Problem</dt><dd>{p.problem}</dd></div><div><dt>My role</dt><dd>{p.role}</dd></div><div><dt>Solution</dt><dd>{p.solution}</dd></div><div><dt>Outcome</dt><dd>{p.outcome}</dd></div></dl><h4>Main features</h4><ul className="feature-list">{p.features.map(f=><li key={f}>{f}</li>)}</ul><div className="tags">{p.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="card-actions">{p.github&&<a href={p.github} target="_blank" rel="noreferrer" className="button secondary"><Github/> GitHub</a>}{p.caseStudy&&<a href={p.caseStudy} className="button secondary"><FileText/> View Case Study</a>}<button className="button primary" type="button" onClick={()=>setSelected(p)}>View Screenshots</button></div></div></motion.article>)}</div><ModalShell open={!!selected} onClose={()=>setSelected(null)} title={`${selected?.title??"Project"} screenshots`}><div className="gallery">{selected?.screenshots.map(s=><figure key={s.url}><img src={s.url} loading="lazy" decoding="async" alt={s.caption}/><figcaption>{s.caption}</figcaption></figure>)}</div></ModalShell></section>}

export function ExperienceSection(){return <section id="experience" className="section"><SectionHeader eyebrow="Professional journey" title="Experience"/><div className="timeline">{experience.map(item=><motion.article {...reveal} key={item.role} className="glass"><Briefcase aria-hidden="true"/><div><p className="eyebrow">{item.period} · {item.company}</p><h3>{item.role}</h3><p>{item.description}</p><div className="tags">{item.skills.map(s=><span key={s}>{s}</span>)}</div></div></motion.article>)}</div></section>}

export function AboutSection(){return <section id="about" className="section"><SectionHeader eyebrow="About me" title="A developer grounded in practical problem-solving"/><div className="two-column"><motion.div {...reveal} className="glass prose-card"><p>I’m Drix Molina, a Full Stack Developer and IT graduate based in the Philippines. I enjoy turning complex workflows into clear, responsive web experiences and supporting the technology behind them.</p><p>My work spans frontend development, system testing, documentation, IT support, and AI-assisted automation. I value dependable solutions, accessible interfaces, and continuous learning.</p></motion.div><motion.aside {...reveal} className="glass education-card"><GraduationCap/><div><p className="eyebrow">Education</p><h3>Far Eastern University – Diliman</h3><p>Bachelor of Science in Information Technology</p><p>Major in Web and Mobile Application Development</p><strong>2022–2026 · Graduate</strong></div></motion.aside></div></section>}

export function SkillsSection(){return <section id="skills" className="section"><SectionHeader eyebrow="Capabilities" title="Skills & Tools"/><div className="skills-grid">{skillGroups.map(([group,skills])=><motion.article {...reveal} key={group} className="glass"><h3>{group}</h3><ul>{skills.map(s=><li key={s}>{s}</li>)}</ul></motion.article>)}</div></section>}

export function CapstoneSection(){return <section id="facilitease-case-study" className="section"><SectionHeader eyebrow="Capstone case study" title="FacilitEASE" description="A web and mobile property management and reservation system for the FEU Diliman Facilities Office."/><div className="case-study glass"><img src="/projects/facilitease-project-demo.jpg" width="1200" height="675" loading="lazy" decoding="async" alt="FacilitEASE capstone project presentation"/><div><h3>From fragmented requests to one coordinated workflow</h3><p><strong>Challenge:</strong> Reservations, requests, inventory, maintenance, property records, and notifications needed a centralized workflow.</p><p><strong>Contribution:</strong> Capstone development, documentation, system testing, UI/UX support, research revisions, and presentation preparation.</p><p><strong>Solution:</strong> Connected web and mobile applications covering reservations, job and service requests, personnel dispatch, records, maintenance, and notifications.</p><div className="card-actions"><a className="button primary" href="/projects/facilitease-paper.pdf" target="_blank" rel="noreferrer"><FileText/> View Research Paper</a><a className="button secondary" href="/projects/facilitease-paper.pdf" download><Download/> Download Paper</a></div></div></div></section>}

export function CredentialsSection(){return <section id="credentials" className="section"><SectionHeader eyebrow="Education & credentials" title="Credentials" description="Academic background, technical certifications, resume, and project resources."/><div className="credential-grid"><article className="glass credential-card"><GraduationCap/><h3>Far Eastern University – Diliman</h3><p>Bachelor of Science in Information Technology</p><p>Major in Web and Mobile Application Development</p><strong>2022–2026 · Graduate</strong></article>{credentials.map(c=><a className="glass credential-card" href={c.href} target="_blank" rel="noreferrer" key={c.title}><FileText/><h3>{c.title}</h3><span>View certificate <ExternalLink/></span></a>)}<a className="glass credential-card" href="/projects/facilitease-paper.pdf" target="_blank" rel="noreferrer"><FileText/><h3>FacilitEASE Research Paper</h3><span>View resource <ExternalLink/></span></a></div></section>}

export function ResumeSection(){const[open,setOpen]=useState(false);return <section id="resume" className="section"><SectionHeader eyebrow="Resume" title="Experience at a glance"/><div className="resume-card glass"><div><h3>Drix Molina · Full Stack Developer</h3><p>Review my education, project work, skills, and experience in an ATS-friendly PDF.</p><div className="card-actions"><button className="button secondary" onClick={()=>setOpen(true)} type="button">Preview Resume</button><a className="button primary" href="/resume/Drix_Molina_Resume.pdf" download><Download/> Download Resume</a></div></div><FileText aria-hidden="true"/></div><ModalShell open={open} onClose={()=>setOpen(false)} title="Drix Molina Resume"><iframe className="pdf-preview" loading="lazy" src="/resume/Drix_Molina_Resume.pdf" title="Drix Molina resume PDF preview"/></ModalShell></section>}

type FormFields={name:string;email:string;message:string;website:string}; const blank:FormFields={name:"",email:"",message:"",website:""};
export function ContactSection(){const[fields,setFields]=useState(blank),[errors,setErrors]=useState<Partial<FormFields>>({}),[status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  const validate=()=>{const next:Partial<FormFields>={};if(fields.name.trim().length<2)next.name="Please enter your name.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fields.email))next.email="Please enter a valid email address.";if(fields.message.trim().length<10)next.message="Please enter at least 10 characters.";setErrors(next);return !Object.keys(next).length};
  const submit=async(e:FormEvent)=>{e.preventDefault();if(status==="sending"||!validate())return;setStatus("sending");try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(fields)});if(!response.ok)throw new Error();setFields(blank);setErrors({});setStatus("success")}catch{setStatus("error")}};
  const update=(key:keyof FormFields,value:string)=>{setFields(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:undefined}));if(status!=="sending")setStatus("idle")};
  return <section id="contact" className="section"><SectionHeader eyebrow="Let’s connect" title="Contact Me" description="Have an opportunity, project, or question? Send a message and I’ll get back to you."/><div className="contact-grid"><div className="glass contact-intro"><Mail/><h3>Start a conversation</h3><p>Email: <a href="mailto:drixmolina31@gmail.com">drixmolina31@gmail.com</a></p><SocialLinks/></div><form className="glass contact-form" onSubmit={submit} noValidate><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off" value={fields.website} onChange={e=>update("website",e.target.value)}/></div>{(["name","email","message"] as const).map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}{key==="message"?<textarea value={fields[key]} onChange={e=>update(key,e.target.value)} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined} rows={6}/>:<input type={key==="email"?"email":"text"} value={fields[key]} onChange={e=>update(key,e.target.value)} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>} {errors[key]&&<span className="field-error" id={`${key}-error`}>{errors[key]}</span>}</label>)}<button className="button primary" type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":<>Send Message <Send/></>}</button><div aria-live="polite" className={`form-status ${status}`}>{status==="success"&&"Message sent successfully. Thank you!"}{status==="error"&&"Your message could not be sent. Your input is still here—please try again."}</div></form></div></section>}

export function Footer(){return <footer><p>© {new Date().getFullYear()} Drix Molina. Built with React and care.</p><a href="#hero">Back to top <ArrowUp/></a></footer>}
